Repository srngch/ngin-xs, pull requests merged in 2022-10, with the labels that each got.

#4 Parse request messages
  Makefile
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/main.cpp
Labels: feature

#7 Handle request syntax error exception
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/macro.hpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: feature

#8 Add Response class
  Makefile
  error_pages/400.html
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/main.cpp
Labels: feature

#11 feat: Implement request validation(#10)
  error_pages/405.html
  error_pages/505.html
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/macro.hpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: feature

#12 feat: Implement GET method for static files(#9)
  error_pages/404.html
  html/index.html
  html/test.html
  html/test/a.html
  html/test/b.html
  html/test/index.html
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: feature

#16 Implement calling CGI program with GET
  error_pages/403.html
  error_pages/500.html
  html/now-html.py
  html/now.py
  html/test/now.py
  srcs/Request.cpp
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/macro.hpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: bug, feature, chore

#20 Implement autoindexing
  Makefile
  srcs/Worker.hpp
  srcs/autoindex/Autoindex.cpp
  srcs/autoindex/Autoindex.hpp
  srcs/autoindex/AutoindexData.cpp
  srcs/autoindex/AutoindexData.hpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: feature

#26 refactor: Change header data type(#24)
  srcs/Cgi.cpp
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Worker.cpp
Labels: refactor

#27 feat: Implement Uri class(#23)
  Makefile
  srcs/Cgi.cpp
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Uri.cpp
  srcs/Uri.hpp
  srcs/Worker.cpp
Labels: feature

#28 feat: Implement DELETE method(#21)
  srcs/Worker.cpp
  srcs/macro.hpp
Labels: feature

#33 feat: Handle chunked request(#13)
  error_pages/501.html
  srcs/Cgi.cpp
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Uri.cpp
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/macro.hpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: bug, feature, refactor

#35 feat: Parse configuration file
  Makefile
  srcs/config/Block.cpp
  srcs/config/Block.hpp
  srcs/config/Config.cpp
  srcs/config/Config.hpp
  srcs/config/webserv.conf
  srcs/main.cpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: feature

#36 feat: Implement directory path redirection(#19)
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Uri.cpp
  srcs/Uri.hpp
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/macro.hpp
Labels: bug, feature

#37 feat: Implement python-cgi(#32)
  Makefile
  cgi-bin/python-cgi.py
  dummy/avatar.png
  dummy/hello.txt
  html/file.py
  html/now-html.py
  html/now.py
  html/readstdin.py
  html/test/now.py
  html/upload.py
  srcs/Cgi.cpp
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Uri.cpp
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: feature

#38 feat: Update function to set response header(#25)
  cgi-bin/python-cgi.py
  html/index.html
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Worker.cpp
  srcs/main.cpp
  srcs/mime.hpp
Labels: bug, feature

#43 feat: Implement CUI client(#41)
  client/Makefile
  client/client.c
  client/not-allowed-method.txt
  client/wrong-http.txt
Labels: feature

#46 feat: Support multipart/form-data file upload via python-cgi
  cgi-bin/python-cgi.py
Labels: feature

#51 Fix CRLF issue when response binary file
  srcs/Cgi.cpp
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Worker.cpp
Labels: bug

#52 feat: Handle Connection header in request(#47)
  srcs/Worker.cpp
  srcs/Worker.hpp
Labels: feature

#53 Limit client max body size
  .gitignore
  error_pages/413.html
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/macro.hpp
Labels: bug, feature

#55 refactor: Refactor exception(#54)
  error_pages/400.html
  error_pages/403.html
  error_pages/404.html
  error_pages/405.html
  error_pages/413.html
  error_pages/500.html
  error_pages/501.html
  error_pages/505.html
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/macro.hpp
Labels: refactor

#56 feat: Implement web client(#40)
  cgi-bin/python-cgi.py
  html/autoindex/hello.html
  html/form.html
  html/index.html
  html/multipart-form.html
  html/test.html
Labels: bug, feature

#58 feat: Implement running multiple servers
  Makefile
  conf/default.conf
  conf/webserv.conf
  srcs/Master.cpp
  srcs/Master.hpp
  srcs/Nginxs.cpp
  srcs/Nginxs.hpp
  srcs/Request.cpp
  srcs/Worker.cpp
  srcs/config/Block.cpp
  srcs/config/Block.hpp
  srcs/config/Config.cpp
  srcs/config/webserv.conf
  srcs/macro.hpp
  srcs/main.cpp
Labels: feature

#60 Apply Config class
  conf/default.conf
  conf/webserv.conf
  error_pages/404.html
  html/avatar.png
  html/bye/hello.html
  html/bye/index.html
  html/dir/index.html
  html/test/dir/a.html
  srcs/Cgi.cpp
  srcs/Cgi.hpp
  srcs/Master.cpp
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Uri.cpp
  srcs/Uri.hpp
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/config/Block.cpp
  srcs/config/Block.hpp
  srcs/config/Config.cpp
  srcs/macro.hpp
  srcs/utils.cpp
Labels: bug, feature

#65 perf: Improve speed(#64)
  srcs/Cgi.cpp
  srcs/Cgi.hpp
  srcs/Nginxs.cpp
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/config/Block.cpp
  srcs/config/Config.cpp
  srcs/config/Config.hpp
  srcs/macro.hpp
  srcs/main.cpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: refactor

#68 refactor: Add typedef(#67)
  conf/webserv.conf
  html/index.html
  srcs/Cgi.cpp
  srcs/Cgi.hpp
  srcs/Master.cpp
  srcs/Master.hpp
  srcs/Nginxs.cpp
  srcs/Nginxs.hpp
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Uri.cpp
  srcs/Uri.hpp
  srcs/Worker.cpp
  srcs/Worker.hpp
  srcs/autoindex/Autoindex.cpp
  srcs/autoindex/Autoindex.hpp
  srcs/autoindex/AutoindexData.cpp
  srcs/autoindex/AutoindexData.hpp
  srcs/config/Block.cpp
  srcs/config/Block.hpp
  srcs/config/Config.cpp
  srcs/config/Config.hpp
  srcs/macro.hpp
  srcs/main.cpp
  srcs/types.hpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: refactor

#70 fix: Add allow header when response 405
  srcs/Worker.cpp
  srcs/utils.cpp
  srcs/utils.hpp
Labels: bug
